Data Encoding

1.Nominal/OHE
2.Label and Ordinal
3.Target Guided Ordinal

Nominal/OHE Encoding

One hot encoding ,also known as nominal encoding,is a technique used to represent categorialdata as numerical data,which is more suitable for ML algorithms.each category is represented as a binary vector where each bit corresponds to a unique category.

For example-
Having 3 colors(Red , BLue,Green):{categorial feature to numerical feature}

Red(1,0,0),blue(0,1,0),Green(0,0,1)

many categorial datset not uses this it give overfitting error

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
df=pd.DataFrame({
    'color':['red','blue','green','yellow','purple']
})

In [4]:
df.head()

    color
0     red
1    blue
2   green
3  yellow
4  purple

In [5]:
#create an instance oh OHE
encoder=OneHotEncoder()

In [11]:
#perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray()#sprase matrix

In [13]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [15]:
encoder_df

   color_blue  color_green  color_purple  color_red  color_yellow
0         0.0          0.0           0.0        1.0           0.0
1         1.0          0.0           0.0        0.0           0.0
2         0.0          1.0           0.0        0.0           0.0
3         0.0          0.0           0.0        0.0           1.0
4         0.0          0.0           1.0        0.0           0.0

In [ ]:
#for new data
encoder.transform([['blue']]).toarray()

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0., 0., 0.]])

In [18]:
pd.concat([df,encoder_df],axis=1)

    color  color_blue  color_green  color_purple  color_red  color_yellow
0     red         0.0          0.0           0.0        1.0           0.0
1    blue         1.0          0.0           0.0        0.0           0.0
2   green         0.0          1.0           0.0        0.0           0.0
3  yellow         0.0          0.0           0.0        0.0           1.0
4  purple         0.0          0.0           1.0        0.0           0.0

Label Encoding

Used to encode categorical data as numerical data

Involves assigning a unique numeric data label to each category in the cariable.The label are usually assigned in alphabetical order or based on the frequency of the categories.

Example:3-color(red,blure,green)-

red=1,blue=2,green=3

In [20]:
df.head()

    color
0     red
1    blue
2   green
3  yellow
4  purple

In [22]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [23]:
lbl_encoder.fit_transform(df[['color']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([3, 0, 1, 4, 2])

In [24]:
lbl_encoder.transform([['red']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([3])

Ordinal Encoding

Used to encode categorical data that have a n intrinsic order or ranking. Each category is assigned a numerical value baes on its position in the order.For eg,categorical  variable"education level" with possible values(high school,colledge,graduate,post-graduate),we can represent it using ordinal encoding:

HS:1,C:2,G:3,PG:4

In [28]:
from sklearn.preprocessing import OrdinalEncoder

In [30]:
df=pd.DataFrame({
    'size':['small','large','medium','small','large','medium']
})

In [31]:
df

     size
0   small
1   large
2  medium
3   small
4   large
5  medium

In [32]:
#create an instance
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [33]:
encoder.fit_transform(df[['size']])

array([[0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.]])

In [34]:
encoder.transform([['small']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

3. Target Guided Ordinal Encoding

Used to encode categorical variable on their relationship with the target value .The encoding technique is useful when we have a categorical variable with a large number of unique categories,we want to use this variable as faeture in our machine learning model.

We replace category in the categorical varibale with a numerical value based on the mean or median of the target varibale for that category.This creates a monotonic relationship between the categoriacl variables and he target variable,which can improve the predictive power of our model.

In [3]:
import pandas as pd
df=pd.DataFrame({
    'city':['New York','London','Paris','tokyo','New Zealand'],
    'price':[200,300,400,230,400]
})

In [4]:
df

          city  price
0     New York    200
1       London    300
2        Paris    400
3        tokyo    230
4  New Zealand    400

In [8]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [9]:
mean_price

{'London': 300.0,
 'New York': 200.0,
 'New Zealand': 400.0,
 'Paris': 400.0,
 'tokyo': 230.0}

In [10]:
df['city_encoded']=df['city'].map(mean_price)

In [11]:
df

          city  price  city_encoded
0     New York    200         200.0
1       London    300         300.0
2        Paris    400         400.0
3        tokyo    230         230.0
4  New Zealand    400         400.0

In [12]:
df[['price','city_encoded']]

   price  city_encoded
0    200         200.0
1    300         300.0
2    400         400.0
3    230         230.0
4    400         400.0

In [13]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]